### ISSUE TITLE
Mines aren't silent

### ISSUE THREAD

**Issue by x0Z3ro0x** [vk2gpz/MineResetLite#3]
No matter what Boolean you use either true or false, mines will still announce when they reset. This isn't a big issue until you start adding multiple mines, then it just spams the world horribly.

**Comment by vk2gpz** [comment]
can you post your config? is your "isSilent:" option set to true?

**Comment by x0Z3ro0x** [comment]
I have used both booleans as stated above. Neither boolean has an effect the plugin announces the reset regardless.

Used true, tested it, same effect. Shutdown server.

Used false, tested it, same effect, Shutdown server.

Retested both a second time after server shutdown.

**Comment by x0Z3ro0x** [comment]
# MineResetLite Configuration File
# If you have multiple worlds, and wish for only the worlds in which your mine resides to receive
# reset notifications, and automatic reset warnings, set this to true.
broadcast-in-world-only: true
# If you only want players nearby the mines to receive reset notifications,
# and automatic reset warnings, set this to true. Note: Currently only broadcasts to players in the mine
broadcast-nearby-only: false
# When true, this config option enables update alerts. I do not send any extra information along when 
# checking, and query a static file hosted on Dropbox. 
check-for-updates: true
# MineResetLite supports multiple languages. Indicate the language to be used here.
# Languages available at the time this config was generated: Danish (thanks Beijiru), Spanish (thanks enetocs), Portuguese (thanks FelipeMarques14), Italian (thanks JoLong)
# Use the following values for these languages: English: 'en', Danish: 'da', Spanish: 'es', Portuguese: 'pt', Italian: 'it', French: 'fr', Dutch: 'nl', Polish: 'pl'
# A fully up-to-date list of languages is available at http://dev.bukkit.org/server-mods/mineresetlite/pages/internationalization/
locale: en

**Comment by vk2gpz** [comment]
so, you've set isSilent: option for each mine?

**Comment by x0Z3ro0x** [comment]
Yes that would be the option I am referring to. To my knowledge there isn't another option that deals with announcing??

**Comment by x0Z3ro0x** [comment]
Not sure if your latest update via:

https://www.spigotmc.org/resources/mineresetlite-with-worldedit-v6-v7-tokenenchant-explosive-support.61713/update?update=274308

is in relation to this. If it isn't I apologize for testing ahead of time. If it was, I just wanted to let you know mines still broadcast regardless of the Boolean. I tested the same way as before.

Shut down the server, tested false, still sent the broadcast.

Shut down the server, tested true, still sent the broadcast.

Thank you in advance for taking the time to work on this! Just let me know when you need me to test.

**Comment by vk2gpz** [comment]
Please attach one of your mine’s config

**Comment by x0Z3ro0x** [comment]
Not sure how this will help you. The mine announces and ignores your isSilent. Period.

```
mine:
  ==: com.koletar.jj.mineresetlite.Mine
  resetDelay: 15
  surface: ''
  maxZ: -116
  tpYaw: 0
  maxY: 84
  maxX: -151
  resetPercent: -1.0
  fillMode: false
  tpPitch: 0
  world: sbmain
  minY: 71
  resetWarnings:
  - '10'
  - '5'
  - '3'
  - '2'
  - '1'
  minX: -166
  composition:
    SAND:0: 0.005
    ANDESITE:0: 0.005
    STONE:0: 0.95
    AIR:0: 0.025
    COAL_ORE:0: 0.005
    DIRT:0: 0.005
    GRANITE:0: 0.005
  potions: {}
  name: mine1
  resetClock: 6
  minZ: -127
  isSilent: false
  tpY: -2147483647
  tpX: 0
  tpZ: 0
```

**Comment by vk2gpz** [comment]
are you serious???
 your "isSilent:" option is "false"...

**Comment by x0Z3ro0x** [comment]
Are you serious? How many times do I have to tell you I have tested it both ways.

**Comment by x0Z3ro0x** [comment]
Apparently I am to stupid to know what a Boolean is or how to use it. So I will paste the config for you again with the same option tested for the FOURTH time. Like I have said before IT DOESN'T MATTER mines still announce.

```
mine:
  ==: com.koletar.jj.mineresetlite.Mine
  resetDelay: 15
  surface: ''
  maxZ: -116
  tpYaw: 0
  maxY: 84
  maxX: -151
  resetPercent: -1.0
  fillMode: false
  tpPitch: 0
  world: sbmain
  minY: 71
  resetWarnings:
  - '10'
  - '5'
  - '3'
  - '2'
  - '1'
  minX: -166
  composition:
    SAND:0: 0.005
    ANDESITE:0: 0.005
    STONE:0: 0.95
    AIR:0: 0.025
    COAL_ORE:0: 0.005
    DIRT:0: 0.005
    GRANITE:0: 0.005
  potions: {}
  name: mine1
  resetClock: 6
  minZ: -127
  isSilent: true
  tpY: -2147483647
  tpX: 0
  tpZ: 0

```
